spring.application.name=ecom-application
spring.h2.console.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/ecomdb
spring.datasource.username=karimK
spring.datasource.password=karimk
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDiialect

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name= MyNewApp
